"""Aumentar longitud del password a 256

Revision ID: 457e6fa05969
Revises: d876529705b9
Create Date: 2024-09-20 11:56:03.300015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457e6fa05969'
down_revision = 'd876529705b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
