"""Añadir Descripción a la tabla de tareas

Revision ID: 5091af971e4e
Revises: 18a3950f103c
Create Date: 2024-09-24 09:33:52.955821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5091af971e4e'
down_revision = '18a3950f103c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
